### ISSUE TITLE
Dialog boxes

### ISSUE THREAD

**Issue by DanielleJude** [jfeiber/buzzer#137]
When a waitress/waiter wants to add but has not put party number or minutes, you should let know they need to add those before they can continue. I ended up clicking the button 5 times before someone told me I need to add the wait time

**Comment by themacexpert** [comment]
We previously had a Bootstrap danger alert in this style:
<img width="794" alt="screen shot 2017-02-12 at 3 07 27 pm" src="https://cloud.githubusercontent.com/assets/5834262/22865575/046bfe8c-f135-11e6-9829-a32492cb99ef.png">

However, we thought this was an intrusive alert because it

- Shifts all the elements of the page down. 
- Creates alert fatigue with users and feels aggressive.

We looked into best practices before concluding that disabling the button was a cleaner and more intuitive solution.
