### ISSUE TITLE
Cellular check

### ISSUE THREAD

**Issue by DanielleJude** [jfeiber/buzzer#139]
Is there a way to warn the user when they are out of cellular range? What happens if they are being called and they don't know? Is there a way for the server to receive heartbeats from buzzers and if they don't respond then something happens? Or the server heartbeat to the buzzer and if they don't get them vibrate and warn the user to get back in range? Or not vibrate but flash a light or some signal. Look up the gossip protocol if you want to do server to buzzers!

**Comment by jfeiber** [comment]
The way it works right now is the buzzer heartbeats to a central API. So there is already buzzer -> server communication. I don't think the gossip protocol really applies here because buzzers don't need to know about the information on other buzzers, they only need to communicate directly to the central API.

Right now the buzzer will give an error if it goes out of cell range, unfortunately it's just a general error. With this current cell modem it's a little tricky to know whether or not an HTTP request failed because of lack of signal or because there was some other problem (garbage serial response from the modem, something went wrong with the server, etc). We'll keep trying to improve that though. 

We're not too concerned about a buzzer being buzzed and the person not knowing currently. A light could be a cool idea, but we're kind of out of money at this point so unfortunately we can't do any serious hardware/PCB revisions like that.
