### ISSUE TITLE
Party Sorting Functionality

### ISSUE THREAD

**Issue by carterjbastian** [jfeiber/buzzer#145]
Right now there doesn't seem to be a way to sort parties. If you have 50+ parties on a crowded night and you have one table of three open up, I would want to be able to sort the waiting parties by wait time. Alternatively, if someone calls to cancel or check on their wait time, it would be nice to sort by the party name to find them quickly.

**Comment by jfeiber** [comment]
Currently the wait list is sorted by elapsed wait time. We're thinking about adding a search functionality to the wait list for the second scenario you described, because if the wait list is really long then sorting it by party name is still a cumbersome way to find a party with a specific name. 

I'm going to close this for now and we'll revisit it if we choose to implement the search functionality.
